//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZH.Models.ZHEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        public int Id { get; set; }
        public Nullable<int> AssignedEmp { get; set; }
        public string FoodType { get; set; }
        public string Quantity { get; set; }
        public int RequestedRes { get; set; }
        public string Status { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual ResturentTable ResturentTable { get; set; }
    }
}
